name: Build Android
on:
  push:
    branches: ["android-app"]
  pull_request:
    branches: ["android-app"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug
